mv './Anguttara Nikaya/Araka.pdf' './Anguttara Nikaya/AN7.74_Araka.pdf'
mv './Anguttara Nikaya/A¦ünanda.pdf' './Anguttara Nikaya/AN9.37_Ánanda.pdf'
mv './Anguttara Nikaya/Bojovni¦ük.pdf' './Anguttara Nikaya/AN4.181_Bojovník.pdf'
mv './Anguttara Nikaya/Bytosti.pdf' './Anguttara Nikaya/AN9.24_Bytosti.pdf'
mv './Anguttara Nikaya/Brahma¦üni.pdf' './Anguttara Nikaya/AN9.38_Brahmáni.pdf'
mv './Anguttara Nikaya/Byt sdruzovan.pdf' './Anguttara Nikaya/AN3.26_Byt sdruzovan.pdf'
mv './Anguttara Nikaya/Byti (Zivot).pdf' './Anguttara Nikaya/AN3.76_Byti (Zivot).pdf'
mv './Anguttara Nikaya/Chteni a usilovani.pdf' './Anguttara Nikaya/AN3.77_Chteni a usilovani.pdf'
mv './Anguttara Nikaya/C¦îiny.pdf' './Anguttara Nikaya/AN4.115_Činy.pdf'
mv './Anguttara Nikaya/Diamant.pdf' './Anguttara Nikaya/AN3.25_Diamant.pdf'
mv './Anguttara Nikaya/Dluh.pdf' './Anguttara Nikaya/AN6.45_Dluh.pdf'
mv './Anguttara Nikaya/Hmota:Tvar.pdf' './Anguttara Nikaya/AN4.65_Hmota:Tvar.pdf'
mv './Anguttara Nikaya/Hne¦îv.pdf' './Anguttara Nikaya/AN4.43_Hněv.pdf'
mv './Anguttara Nikaya/Kalakarama sutta.pdf' './Anguttara Nikaya/AN4.24_Kalakarama sutta.pdf'
mv './Anguttara Nikaya/Kamenny¦ü pili¦ür¦î.pdf' './Anguttara Nikaya/AN9.26_Kamenný pilíř.pdf'
mv './Anguttara Nikaya/Koka¦älika.pdf' './Anguttara Nikaya/AN10.89_Kokālika.pdf'
mv './Anguttara Nikaya/Kotthita.pdf' './Anguttara Nikaya/AN9.13_Kotthita.pdf'
mv './Anguttara Nikaya/Kra¦üva.pdf' './Anguttara Nikaya/AN9.35_Kráva.pdf'
mv './Anguttara Nikaya/Laska a Nenavist.pdf' './Anguttara Nikaya/AN4.200_Laska a Nenavist.pdf'
mv './Anguttara Nikaya/Lev.pdf' './Anguttara Nikaya/AN4.33_Lev.pdf'
mv './Anguttara Nikaya/Mallika.pdf' './Anguttara Nikaya/AN4.197_Mallika.pdf'
mv './Anguttara Nikaya/Migasala.pdf' './Anguttara Nikaya/AN6.44_Migasala.pdf'
mv './Anguttara Nikaya/Mniska.pdf' './Anguttara Nikaya/AN4.159_Mniska.pdf'
mv './Anguttara Nikaya/Naga.pdf' './Anguttara Nikaya/AN6.43_Naga.pdf'
mv './Anguttara Nikaya/Nandamata.pdf' './Anguttara Nikaya/AN7.53_Nandamata.pdf'
mv './Anguttara Nikaya/Nebezpeci.pdf' './Anguttara Nikaya/AN3.62_Nebezpeci.pdf'
mv './Anguttara Nikaya/Odloucen.pdf' './Anguttara Nikaya/AN4.38_Odloucen.pdf'
mv './Anguttara Nikaya/Okovy.pdf' './Anguttara Nikaya/AN4.88_Okovy.pdf'
mv './Anguttara Nikaya/Ota¦üzky.pdf' './Anguttara Nikaya/AN4.42_Otázky.pdf'
mv './Anguttara Nikaya/Pacetana.pdf' './Anguttara Nikaya/AN3.15_Pacetana.pdf'
mv './Anguttara Nikaya/Podmi¦ünky sve¦îta (1).pdf' './Anguttara Nikaya/AN8.5_Podmínky světa (1).pdf'
mv './Anguttara Nikaya/Potaliya.pdf' './Anguttara Nikaya/AN4.100_Potaliya.pdf'
mv './Anguttara Nikaya/Poleno z pohr¦îebni¦ü hranice.pdf' './Anguttara Nikaya/AN4.95_Poleno z pohřební hranice.pdf'
mv './Anguttara Nikaya/Poutavy¦ü (1).pdf' './Anguttara Nikaya/AN8.17_Poutavý (1).pdf'
mv './Anguttara Nikaya/Pronikavy.pdf' './Anguttara Nikaya/AN6.63_Pronikavy.pdf'
mv './Anguttara Nikaya/Sexualni styk.pdf' './Anguttara Nikaya/AN7.50_Sexualni styk.pdf'
mv './Anguttara Nikaya/Situace.pdf' './Anguttara Nikaya/AN5.48_Situace.pdf'
mv './Anguttara Nikaya/Syn.pdf' './Anguttara Nikaya/AN4.87_Syn.pdf'
mv './Anguttara Nikaya/Uvedomeni smrti.pdf' './Anguttara Nikaya/AN6.19_Uvedomeni smrti.pdf'
mv './Anguttara Nikaya/Vnimani.pdf' './Anguttara Nikaya/AN7.49_Vnimani.pdf'
mv './Anguttara Nikaya/Zakor¦îene¦îny.pdf' './Anguttara Nikaya/AN8.83_Zakořeněny.pdf'
mv './Anguttara Nikaya/Zmije.pdf' './Anguttara Nikaya/AN4.110_Zmije.pdf'
mv './Anguttara Nikaya/Poutavy¦ü (2).pdf' './Anguttara Nikaya/AN8.18_Poutavý (2).pdf'
mv './Anguttara Nikaya/Sama¦ädhi.pdf' './Anguttara Nikaya/AN4.41_Samādhi.pdf'
mv './Anguttara Nikaya/Sve¦ît.pdf' './Anguttara Nikaya/AN4.23_Svět.pdf'
mv './Anguttara Nikaya/Te¦ümata.pdf' './Anguttara Nikaya/AN5.57_Témata.pdf'
mv './Anguttara Nikaya/Uda¦äyi¦ä.pdf' './Anguttara Nikaya/AN5.159_Udāyī.pdf'
mv './Anguttara Nikaya/Usta¦üni¦ü.pdf' './Anguttara Nikaya/AN5.166_Ustání.pdf'
mv './Anguttara Nikaya/V jake¦ümkoli mi¦üste¦î.pdf' './Anguttara Nikaya/AN5.134_V jakémkoli místě.pdf'
mv './Anguttara Nikaya/Vappa.pdf' './Anguttara Nikaya/AN4.195_Vappa.pdf'
mv './Anguttara Nikaya/Ve Str¦îedu.pdf' './Anguttara Nikaya/AN6.61_Ve Středu.pdf'
mv './Anguttara Nikaya/Vr¦îed.pdf' './Anguttara Nikaya/AN9.15_Vřed.pdf'
mv './Anguttara Nikaya/Zlost (2).pdf' './Anguttara Nikaya/AN9.30_Zlost (2).pdf'
mv './Anguttara Nikaya/(Po)ka¦üra¦üni¦ü.pdf' './Anguttara Nikaya/AN5.167_(Po)kárání.pdf'
mv './Anguttara Nikaya/Ba¦üzlivost.pdf' './Anguttara Nikaya/AN5.158_Bázlivost.pdf'
mv './Anguttara Nikaya/Brahmanske pravdy.pdf' './Anguttara Nikaya/AN4.185_Brahmanske pravdy.pdf'
mv './Anguttara Nikaya/Hluboko potopeny.pdf' './Anguttara Nikaya/AN4.86_Hluboko potopeny.pdf'
mv './Anguttara Nikaya/Jeden Narus¦îuje.pdf' './Anguttara Nikaya/AN5.142_Jeden Narušuje.pdf'
mv './Anguttara Nikaya/Kladeni¦ü ota¦üzek.pdf' './Anguttara Nikaya/AN5.165_Kladení otázek.pdf'
mv './Anguttara Nikaya/Manz¦îelky.pdf' './Anguttara Nikaya/AN7.63_Manželky.pdf'
mv './Anguttara Nikaya/Nazirani.pdf' './Anguttara Nikaya/AN4.89_Nazirani.pdf'
mv './Anguttara Nikaya/Odstrane¦îni¦ü rozhor¦îc¦îeni¦ü.pdf' './Anguttara Nikaya/AN5.162_Odstranění rozhořčení.pdf'
mv './Anguttara Nikaya/Podmi¦ünky sve¦îta (2).pdf' './Anguttara Nikaya/AN8.6_Podmínky světa (2).pdf'
mv './Anguttara Nikaya/R¦îec¦î jako hnu¦Őj (lejno).pdf' './Anguttara Nikaya/AN3.28_Řeč jako hnůj (lejno).pdf'
mv './Anguttara Nikaya/Sariputta.pdf' './Anguttara Nikaya/AN3.33_Sariputta.pdf'
mv './Anguttara Nikaya/S¦îpatne¦î adresovana¦ü r¦îec¦î.pdf' './Anguttara Nikaya/AN5.157_Špatně adresovaná řeč.pdf'
mv './Anguttara Nikaya/Zhnusenost.pdf' './Anguttara Nikaya/AN3.27_Zhnusenost.pdf'
mv './Anguttara Nikaya/Zlost (1).pdf' './Anguttara Nikaya/AN9.29_Zlost (1).pdf'
mv './Digha Nikaya/Kralovo zreknuti se.pdf' './Digha Nikaya/DN17_Kralovo zreknuti se.pdf'
mv './Digha Nikaya/Opora:zakladna.pdf' './Digha Nikaya/DN11.85_Opora:zakladna.pdf'
mv './Digha Nikaya/Pa¦äya¦äsi sutta.pdf' './Digha Nikaya/DN23_Pāyāsi sutta.pdf'
mv './Digha Nikaya/Stavy ve¦îdomi¦ü.pdf' './Digha Nikaya/DN9_Stavy vědomí.pdf'
mv './Digha Nikaya/Velky Lvi Rev k Udumbarikanum.pdf' './Digha Nikaya/DN25_Velky Lvi Rev k Udumbarikanum.pdf'
mv './Digha Nikaya/Zahanbena¦ü py¦ücha.pdf' './Digha Nikaya/DN3_Zahanbená pýcha.pdf'
mv './Digha Nikaya/Znalost Pocatku.pdf' './Digha Nikaya/DN27_Znalost Pocatku.pdf'
mv './Digha Nikaya/Cesta k Brahmovi (Bohu).pdf' './Digha Nikaya/DN13_Cesta k Brahmovi (Bohu).pdf'
mv './Digha Nikaya/Lvi rev k roztoceni kola.pdf' './Digha Nikaya/DN26_Lvi rev k roztoceni kola.pdf'
mv './Majjhima Nikaya/Dhananjani.pdf' './Majjhima Nikaya/MN97_Dhananjani.pdf'
mv './Majjhima Nikaya/Expozice Elementu:Prvku.pdf' './Majjhima Nikaya/MN140_Expozice Elementu:Prvku.pdf'
mv './Majjhima Nikaya/Ganaka Moggalla¦änovi.pdf' './Majjhima Nikaya/MN107_Ganaka Moggallānovi.pdf'
mv './Majjhima Nikaya/Hrnc¦îi¦ür¦î Ghatikara.pdf' './Majjhima Nikaya/MN81_Hrnčíř Ghatikara.pdf'
mv './Majjhima Nikaya/Jedna skvela noc.pdf' './Majjhima Nikaya/MN131_Jedna skvela noc.pdf'
mv './Majjhima Nikaya/K Dighanakhovi.pdf' './Majjhima Nikaya/MN74_K Dighanakhovi.pdf'
mv './Majjhima Nikaya/Kratsi sdeleni Rahulovi.pdf' './Majjhima Nikaya/MN147_Kratsi sdeleni Rahulovi.pdf'
mv './Majjhima Nikaya/Krats¦îi¦ü rozprava o kona¦üni¦ü.pdf' './Majjhima Nikaya/MN135_Kratší rozprava o konání.pdf'
mv './Majjhima Nikaya/Magandiya.pdf' './Majjhima Nikaya/MN75_Magandiya.pdf'
mv './Majjhima Nikaya/Nandakovo sdeleni.pdf' './Majjhima Nikaya/MN146_Nandakovo sdeleni.pdf'
mv './Majjhima Nikaya/O Angulimalovi.pdf' './Majjhima Nikaya/MN86_O Angulimalovi.pdf'
mv './Majjhima Nikaya/Oc¦îis¦ît¦îova¦üni¦ü almuz¦îni¦üho ji¦üdla.pdf' './Majjhima Nikaya/MN151_Očišťování almužního jídla.pdf'
mv './Majjhima Nikaya/Podobenstvi¦ü o kr¦îepelce.pdf' './Majjhima Nikaya/MN66_Podobenství o křepelce.pdf'
mv './Majjhima Nikaya/Rozbor uryvku recitace.pdf' './Majjhima Nikaya/MN138_Rozbor uryvku recitace.pdf'
mv './Majjhima Nikaya/Sdeleni Anathapindikovi.pdf' './Majjhima Nikaya/MN143_Sdeleni Anathapindikovi.pdf'
mv './Majjhima Nikaya/Sdeleni Channovi.pdf' './Majjhima Nikaya/MN144_Sdeleni Channovi.pdf'
mv './Majjhima Nikaya/S¦îest sad po s¦îesti.pdf' './Majjhima Nikaya/MN148_Šest sad po šesti.pdf'
mv './Majjhima Nikaya/V Devadaze.pdf' './Majjhima Nikaya/MN101_V Devadaze.pdf'
mv './Majjhima Nikaya/Vyklad prvku (elementu).pdf' './Majjhima Nikaya/MN140_Vyklad prvku (elementu).pdf'
mv './Majjhima Nikaya/Vy¦üklad o Bez-rozporu.pdf' './Majjhima Nikaya/MN139_Výklad o Bez-rozporu.pdf'
mv './Majjhima Nikaya/Zrozeno z Milovanych.pdf' './Majjhima Nikaya/MN87_Zrozeno z Milovanych.pdf'
mv './Majjhima Nikaya/Culasakuludayi Sutta.pdf' './Majjhima Nikaya/MN79_Culasakuludayi Sutta.pdf'
mv './Majjhima Nikaya/Doporuc¦îeni¦ü Punnovi.pdf' './Majjhima Nikaya/MN145_Doporučení Punnovi.pdf'
mv './Majjhima Nikaya/Kratsi rozprava o prazdnote.pdf' './Majjhima Nikaya/MN121_Kratsi rozprava o prazdnote.pdf'
mv './Majjhima Nikaya/O kor¦îeni vs¦îech ve¦îci¦ü.pdf' './Majjhima Nikaya/MN1_O kořeni všech věcí.pdf'
mv './Majjhima Nikaya/Va¦äsettha Sutta.pdf' './Majjhima Nikaya/MN98_Vāsettha Sutta.pdf'
mv './Samyutta Nikaya/Asketicka¦ü praxe.pdf' './Samyutta Nikaya/SN4.1_Asketická praxe.pdf'
mv './Samyutta Nikaya/At -atika.pdf' './Samyutta Nikaya/SN12.45_At -atika.pdf'
mv './Samyutta Nikaya/A¦änanda.pdf' './Samyutta Nikaya/SN22.38_Ānanda.pdf'
mv './Samyutta Nikaya/Brahman Unnabha.pdf' './Samyutta Nikaya/SN51.15_Brahman Unnabha.pdf'
mv './Samyutta Nikaya/Br¦îemeno.pdf' './Samyutta Nikaya/SN22.22_Břemeno.pdf'
mv './Samyutta Nikaya/Byt pohlcen.pdf' './Samyutta Nikaya/SN22.79_Byt pohlcen.pdf'
mv './Samyutta Nikaya/Cesta.pdf' './Samyutta Nikaya/SN22.44_Cesta.pdf'
mv './Samyutta Nikaya/Cihlova Hala.pdf' './Samyutta Nikaya/SN14.13_Cihlova Hala.pdf'
mv './Samyutta Nikaya/Dhananjani.pdf' './Samyutta Nikaya/SN7.1_Dhananjani.pdf'
mv './Samyutta Nikaya/Faze agregatu ulpivani.pdf' './Samyutta Nikaya/SN22.56_Faze agregatu ulpivani.pdf'
mv './Samyutta Nikaya/Gavampati.pdf' './Samyutta Nikaya/SN56.30_Gavampati.pdf'
mv './Samyutta Nikaya/Genialni prohlaseni.pdf' './Samyutta Nikaya/SN22.55_Genialni prohlaseni.pdf'
mv './Samyutta Nikaya/Indaka.pdf' './Samyutta Nikaya/SN10.1_Indaka.pdf'
mv './Samyutta Nikaya/Jako mesic.pdf' './Samyutta Nikaya/SN16.3_Jako mesic.pdf'
mv './Samyutta Nikaya/Jambukhadaka.pdf' './Samyutta Nikaya/SN38.1_Jambukhadaka.pdf'
mv './Samyutta Nikaya/Jestrab.pdf' './Samyutta Nikaya/SN47.6_Jestrab.pdf'
mv './Samyutta Nikaya/Jisty Brahman.pdf' './Samyutta Nikaya/SN12.46_Jisty Brahman.pdf'
mv './Samyutta Nikaya/Kasi Bha¦äradva¦äja.pdf' './Samyutta Nikaya/SN7.11_Kasi Bhāradvāja.pdf'
mv './Samyutta Nikaya/Khemaka.pdf' './Samyutta Nikaya/SN22.89_Khemaka.pdf'
mv './Samyutta Nikaya/Koc¦îka.pdf' './Samyutta Nikaya/SN20.10_Kočka.pdf'
mv './Samyutta Nikaya/Krehky.pdf' './Samyutta Nikaya/SN22.32_Krehky.pdf'
mv './Samyutta Nikaya/Kus pe¦îny.pdf' './Samyutta Nikaya/SN22.95_Kus pěny.pdf'
mv './Samyutta Nikaya/Ma¦älunkyaputta.pdf' './Samyutta Nikaya/SN35.95_Mālunkyaputta.pdf'
mv './Samyutta Nikaya/Nejkrasnejsi divka v zemi.pdf' './Samyutta Nikaya/SN47.20_Nejkrasnejsi divka v zemi.pdf'
mv './Samyutta Nikaya/Neni vase.pdf' './Samyutta Nikaya/SN35.101_Neni vase.pdf'
mv './Samyutta Nikaya/Obloha.pdf' './Samyutta Nikaya/SN36.12_Obloha.pdf'
mv './Samyutta Nikaya/Osetrovna.pdf' './Samyutta Nikaya/SN36.7_Osetrovna.pdf'
mv './Samyutta Nikaya/Podobenstvi o velke klade.pdf' './Samyutta Nikaya/SN35.241_Podobenstvi o velke klade.pdf'
mv './Samyutta Nikaya/Prirovnani k loutne.pdf' './Samyutta Nikaya/SN35.246_Prirovnani k loutne.pdf'
mv './Samyutta Nikaya/Rozdilnost Vnimani.pdf' './Samyutta Nikaya/SN14.7_Rozdilnost Vnimani.pdf'
mv './Samyutta Nikaya/Sa¦äketa.pdf' './Samyutta Nikaya/SN48.43_Sāketa.pdf'
mv './Samyutta Nikaya/Sedaka.pdf' './Samyutta Nikaya/SN47.19_Sedaka.pdf'
mv './Samyutta Nikaya/Sedm pripadu.pdf' './Samyutta Nikaya/SN22.57_Sedm pripadu.pdf'
mv './Samyutta Nikaya/Spekulace o Svete.pdf' './Samyutta Nikaya/SN54.41_Spekulace o Svete.pdf'
mv './Samyutta Nikaya/S¦îpatne¦ü zacha¦üzeni¦ü.pdf' './Samyutta Nikaya/SN7.2_Špatné zacházení.pdf'
mv './Samyutta Nikaya/Tvorove¦ü.pdf' './Samyutta Nikaya/SN56.36_Tvorové.pdf'
mv './Samyutta Nikaya/Vakkali.pdf' './Samyutta Nikaya/SN22.87_Vakkali.pdf'
mv './Samyutta Nikaya/Voditko (1).pdf' './Samyutta Nikaya/SN22.99_Voditko (1).pdf'
mv './Samyutta Nikaya/Voditko (2).pdf' './Samyutta Nikaya/SN22.100_Voditko (2).pdf'
mv './Samyutta Nikaya/Yamaka.pdf' './Samyutta Nikaya/SN22.85_Yamaka.pdf'
mv './Samyutta Nikaya/Mys¦îlenky.pdf' './Samyutta Nikaya/SN56.7_Myšlenky.pdf'
mv './Samyutta Nikaya/Neklid skrze ulpivani.pdf' './Samyutta Nikaya/SN22.7_Neklid skrze ulpivani.pdf'
mv './Samyutta Nikaya/Nemocen.pdf' './Samyutta Nikaya/SN55.54_Nemocen.pdf'
mv './Samyutta Nikaya/O samote.pdf' './Samyutta Nikaya/SN36.11_O samote.pdf'
mv './Samyutta Nikaya/Ocean.pdf' './Samyutta Nikaya/SN35.228_Ocean.pdf'
mv './Samyutta Nikaya/Parileyya.pdf' './Samyutta Nikaya/SN22.81_Parileyya.pdf'
mv './Samyutta Nikaya/Prodlevani (1).pdf' './Samyutta Nikaya/SN45.11_Prodlevani (1).pdf'
mv './Samyutta Nikaya/Prodlevani (2).pdf' './Samyutta Nikaya/SN45.12_Prodlevani (2).pdf'
mv './Samyutta Nikaya/Propast.pdf' './Samyutta Nikaya/SN36.4_Propast.pdf'
mv './Samyutta Nikaya/Rozmy¦üs¦îleni¦ü.pdf' './Samyutta Nikaya/SN56.8_Rozmýšlení.pdf'
mv './Samyutta Nikaya/Sakkanamaka.pdf' './Samyutta Nikaya/SN10.2_Sakkanamaka.pdf'
mv './Samyutta Nikaya/Sbe¦îrac¦î almuz¦îen.pdf' './Samyutta Nikaya/SN22.80_Sběrač almužen.pdf'
mv './Samyutta Nikaya/Seminka.pdf' './Samyutta Nikaya/SN22.54_Seminka.pdf'
mv './Samyutta Nikaya/Svazek jecmene.pdf' './Samyutta Nikaya/SN35.248_Svazek jecmene.pdf'
mv './Samyutta Nikaya/Te¦îlo.pdf' './Samyutta Nikaya/SN46.2_Tělo.pdf'
mv './Samyutta Nikaya/Timbaruka.pdf' './Samyutta Nikaya/SN12.18_Timbaruka.pdf'
mv './Samyutta Nikaya/Upasena.pdf' './Samyutta Nikaya/SN35.69_Upasena.pdf'
mv './Samyutta Nikaya/Ve Versich.pdf' './Samyutta Nikaya/SN14.16_Ve Versich.pdf'
mv './Samyutta Nikaya/Vznik.pdf' './Samyutta Nikaya/SN47.42_Vznik.pdf'
mv './Samyutta Nikaya/Z bli¦üzke¦üho br¦îehu.pdf' './Samyutta Nikaya/SN51.1_Z blízkého břehu.pdf'
mv './Samyutta Nikaya/Zlodej pachu.pdf' './Samyutta Nikaya/SN9.14_Zlodej pachu.pdf'
mv './Samyutta Nikaya/Arrahanti.pdf' './Samyutta Nikaya/SN22.76_Arrahanti.pdf'
mv './Samyutta Nikaya/Asibandhakaputta.pdf' './Samyutta Nikaya/SN42.6_Asibandhakaputta.pdf'
mv './Samyutta Nikaya/Babic¦îka.pdf' './Samyutta Nikaya/SN3.22_Babička.pdf'
mv './Samyutta Nikaya/Brahman Unnabha (Indriyasamyutta).pdf' './Samyutta Nikaya/SN48.42_Brahman Unnabha (Indriyasamyutta).pdf'
mv './Samyutta Nikaya/Dojit na konec sveta 2.pdf' './Samyutta Nikaya/SN35.116_Dojit na konec sveta 2.pdf'
mv './Samyutta Nikaya/Hranic¦îni¦ü pili¦ür¦î.pdf' './Samyutta Nikaya/SN56.39_Hraniční pilíř.pdf'
mv './Samyutta Nikaya/Kra¦ülovsky¦ü slon.pdf' './Samyutta Nikaya/SN4.2_Královský slon.pdf'
mv './Samyutta Nikaya/Mahaku¦Őv za¦üzrak.pdf' './Samyutta Nikaya/SN41.4_Mahakův zázrak.pdf'
mv './Samyutta Nikaya/Podobenstvi o Zmijich.pdf' './Samyutta Nikaya/SN35.238_Podobenstvi o Zmijich.pdf'
mv './Samyutta Nikaya/Sa¦üm Sobe¦î Ostrovem.pdf' './Samyutta Nikaya/SN22.43_Sám Sobě Ostrovem.pdf'
mv './Samyutta Nikaya/Sto kopi¦ü.pdf' './Samyutta Nikaya/SN56.35_Sto kopí.pdf'
mv './Samyutta Nikaya/Vnimani pomijivosti.pdf' './Samyutta Nikaya/SN22.102_Vnimani pomijivosti.pdf'
mv './Samyutta Nikaya/Vstup do proudu.pdf' './Samyutta Nikaya/SN24.1_Vstup do proudu.pdf'
mv './Samyutta Nikaya/Nepravidelne poradi.pdf' './Samyutta Nikaya/SN48.40_Nepravidelne poradi.pdf'
mv './Samyutta Nikaya/Podobenstvi o zelve.pdf' './Samyutta Nikaya/SN35.240_Podobenstvi o zelve.pdf'
mv './Samyutta Nikaya/Pr¦îed ti¦üm nez¦î.pdf' './Samyutta Nikaya/SN51.11_Před tím než.pdf'
mv './Samyutta Nikaya/Strom Kimsuka.pdf' './Samyutta Nikaya/SN35.245_Strom Kimsuka.pdf'
mv './Samyutta Nikaya/Uplnkova noc.pdf' './Samyutta Nikaya/SN22.82_Uplnkova noc.pdf'
mv './Samyutta Nikaya/Vy¦üchodni¦ü vra¦ütnice.pdf' './Samyutta Nikaya/SN48.44_Východní vrátnice.pdf'
mv './Khuddaka Nikaya - Petavatthu/Had.pdf' './Khuddaka Nikaya - Petavatthu/Pv1.12_Had.pdf'
mv './Khuddaka Nikaya - Petavatthu/Mattakundali.pdf' './Khuddaka Nikaya - Petavatthu/Pv2.5_Mattakundali.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Miluji¦üci¦ü Laskavost.pdf' './Khuddaka Nikaya - Suttanipāta/Snp1.8_Milující Laskavost.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Mora¦ülni¦ü ostuda.pdf' './Khuddaka Nikaya - Suttanipāta/Snp2.3_Morální ostuda.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Mrs¦îina.pdf' './Khuddaka Nikaya - Suttanipāta/Snp2.3_Mršina.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Vyvrhel.pdf' './Khuddaka Nikaya - Suttanipāta/Snp1.7_Vyvrhel.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Cunda.pdf' './Khuddaka Nikaya - Suttanipāta/Snp1.5_Cunda.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Kasibha¦äradva¦äja.pdf' './Khuddaka Nikaya - Suttanipāta/Snp1.4_Kasibhāradvāja.pdf'
mv './Khuddaka Nikaya - Suttanipāta/Vi¦üte¦îzstvi¦ü.pdf' './Khuddaka Nikaya - Suttanipāta/Snp1.11_Vítězství.pdf'
mv './numbered.pdf' './numbered.html_Tipitaka cesky.pdf'
