mv 'Digha Nikaya/Cesta k Brahmovi (Bohu).html' 'Digha Nikaya/DN13_Cesta k Brahmovi (Bohu).html'
mv 'Digha Nikaya/Kralovo zreknuti se.html' 'Digha Nikaya/DN17_Kralovo zreknuti se.html'
mv 'Digha Nikaya/Lvi rev k roztoceni kola.html' 'Digha Nikaya/DN26_Lvi rev k roztoceni kola.html'
mv 'Digha Nikaya/Opora:zakladna.html' 'Digha Nikaya/DN11.85_Opora:zakladna.html'
mv 'Digha Nikaya/Pa¦äya¦äsi sutta.html' 'Digha Nikaya/DN23_Pa¦äya¦äsi sutta.html'
mv 'Digha Nikaya/Stavy ve¦îdomi¦ü.html' 'Digha Nikaya/DN9_Stavy ve¦îdomi¦ü.html'
mv 'Digha Nikaya/Velky Lvi Rev k Udumbarikanum 2.html' 'Digha Nikaya/DN25_Velky Lvi Rev k Udumbarikanum 2.html'
mv 'Digha Nikaya/Velky Lvi Rev k Udumbarikanum.html' 'Digha Nikaya/DN25_Velky Lvi Rev k Udumbarikanum.html'
mv 'Digha Nikaya/Zahanbena¦ü py¦ücha.html' 'Digha Nikaya/DN3_Zahanbena¦ü py¦ücha.html'
mv 'Digha Nikaya/Znalost Pocatku.html' 'Digha Nikaya/DN27_Znalost Pocatku.html'
