mv 'Samyutta Nikaya/Arrahanti.html' 'Samyutta Nikaya/SN22.76_Arrahanti.html'
mv 'Samyutta Nikaya/Asibandhakaputta.html' 'Samyutta Nikaya/SN42.6_Asibandhakaputta.html'
mv 'Samyutta Nikaya/Asketicka¦ü praxe.html' 'Samyutta Nikaya/SN4.1_Asketicka¦ü praxe.html'
mv 'Samyutta Nikaya/At -atika.html' 'Samyutta Nikaya/SN12.45_At -atika.html'
mv 'Samyutta Nikaya/A¦änanda.html' 'Samyutta Nikaya/SN22.38_A¦änanda.html'
mv 'Samyutta Nikaya/Babic¦îka.html' 'Samyutta Nikaya/SN3.22_Babic¦îka.html'
mv 'Samyutta Nikaya/Brahman Unnabha (Indriyasamyutta).html' 'Samyutta Nikaya/SN48.42_Brahman Unnabha (Indriyasamyutta).html'
mv 'Samyutta Nikaya/Brahman Unnabha.html' 'Samyutta Nikaya/SN51.15_Brahman Unnabha.html'
mv 'Samyutta Nikaya/Br¦îemeno.html' 'Samyutta Nikaya/SN22.22_Br¦îemeno.html'
mv 'Samyutta Nikaya/Byt pohlcen.html' 'Samyutta Nikaya/SN22.79_Byt pohlcen.html'
mv 'Samyutta Nikaya/Cesta.html' 'Samyutta Nikaya/SN22.44_Cesta.html'
mv 'Samyutta Nikaya/Cihlova Hala.html' 'Samyutta Nikaya/SN14.13_Cihlova Hala.html'
mv 'Samyutta Nikaya/Dhananjani.html' 'Samyutta Nikaya/SN7.1_Dhananjani.html'
mv 'Samyutta Nikaya/Dojit na konec sveta 2.html' 'Samyutta Nikaya/SN35.116_Dojit na konec sveta 2.html'
mv 'Samyutta Nikaya/Faze agregatu ulpivani.html' 'Samyutta Nikaya/SN22.56_Faze agregatu ulpivani.html'
mv 'Samyutta Nikaya/Gavampati.html' 'Samyutta Nikaya/SN56.30_Gavampati.html'
mv 'Samyutta Nikaya/Genialni prohlaseni.html' 'Samyutta Nikaya/SN22.55_Genialni prohlaseni.html'
mv 'Samyutta Nikaya/Hranic¦îni¦ü pili¦ür¦î.html' 'Samyutta Nikaya/SN56.39_Hranic¦îni¦ü pili¦ür¦î.html'
mv 'Samyutta Nikaya/Indaka.html' 'Samyutta Nikaya/SN10.1_Indaka.html'
mv 'Samyutta Nikaya/Jako mesic.html' 'Samyutta Nikaya/SN16.3_Jako mesic.html'
mv 'Samyutta Nikaya/Jambukhadaka.html' 'Samyutta Nikaya/SN38.1_Jambukhadaka.html'
mv 'Samyutta Nikaya/Jestrab.html' 'Samyutta Nikaya/SN47.6_Jestrab.html'
mv 'Samyutta Nikaya/Jisty Brahman.html' 'Samyutta Nikaya/SN12.46_Jisty Brahman.html'
mv 'Samyutta Nikaya/Kasi Bha¦äradva¦äja.html' 'Samyutta Nikaya/SN7.11_Kasi Bha¦äradva¦äja.html'
mv 'Samyutta Nikaya/Khemaka.html' 'Samyutta Nikaya/SN22.89_Khemaka.html'
mv 'Samyutta Nikaya/Koc¦îka.html' 'Samyutta Nikaya/SN20.10_Koc¦îka.html'
mv 'Samyutta Nikaya/Kra¦ülovsky¦ü slon.html' 'Samyutta Nikaya/SN4.2_Kra¦ülovsky¦ü slon.html'
mv 'Samyutta Nikaya/Krehky.html' 'Samyutta Nikaya/SN22.32_Krehky.html'
mv 'Samyutta Nikaya/Kus pe¦îny.html' 'Samyutta Nikaya/SN22.95_Kus pe¦îny.html'
mv 'Samyutta Nikaya/Ma¦älunkyaputta.html' 'Samyutta Nikaya/SN35.95_Ma¦älunkyaputta.html'
mv 'Samyutta Nikaya/Mahaku¦Őv za¦üzrak.html' 'Samyutta Nikaya/SN41.4_Mahaku¦Őv za¦üzrak.html'
mv 'Samyutta Nikaya/Nejkrasnejsi divka v zemi.html' 'Samyutta Nikaya/SN47.20_Nejkrasnejsi divka v zemi.html'
mv 'Samyutta Nikaya/Neni vase.html' 'Samyutta Nikaya/SN35.101_Neni vase.html'
mv 'Samyutta Nikaya/Obloha.html' 'Samyutta Nikaya/SN36.12_Obloha.html'
mv 'Samyutta Nikaya/Osetrovna.html' 'Samyutta Nikaya/SN36.7_Osetrovna.html'
mv 'Samyutta Nikaya/Podobenstvi o Zmijich.html' 'Samyutta Nikaya/SN35.238_Podobenstvi o Zmijich.html'
mv 'Samyutta Nikaya/Podobenstvi o velke klade.html' 'Samyutta Nikaya/SN35.241_Podobenstvi o velke klade.html'
mv 'Samyutta Nikaya/Prirovnani k loutne.html' 'Samyutta Nikaya/SN35.246_Prirovnani k loutne.html'
mv 'Samyutta Nikaya/Rozdilnost Vnimani.html' 'Samyutta Nikaya/SN14.7_Rozdilnost Vnimani.html'
mv 'Samyutta Nikaya/Sa¦äketa.html' 'Samyutta Nikaya/SN48.43_Sa¦äketa.html'
mv 'Samyutta Nikaya/Sa¦üm Sobe¦î Ostrovem.html' 'Samyutta Nikaya/SN22.43_Sa¦üm Sobe¦î Ostrovem.html'
mv 'Samyutta Nikaya/Sedaka.html' 'Samyutta Nikaya/SN47.19_Sedaka.html'
mv 'Samyutta Nikaya/Sedm pripadu.html' 'Samyutta Nikaya/SN22.57_Sedm pripadu.html'
mv 'Samyutta Nikaya/Spekulace o Svete.html' 'Samyutta Nikaya/SN54.41_Spekulace o Svete.html'
mv 'Samyutta Nikaya/Sto kopi¦ü.html' 'Samyutta Nikaya/SN56.35_Sto kopi¦ü.html'
mv 'Samyutta Nikaya/S¦îpatne¦ü zacha¦üzeni¦ü.html' 'Samyutta Nikaya/SN7.2_S¦îpatne¦ü zacha¦üzeni¦ü.html'
mv 'Samyutta Nikaya/Tvorove¦ü.html' 'Samyutta Nikaya/SN56.36_Tvorove¦ü.html'
mv 'Samyutta Nikaya/Vakkali.html' 'Samyutta Nikaya/SN22.87_Vakkali.html'
mv 'Samyutta Nikaya/Vnimani pomijivosti.html' 'Samyutta Nikaya/SN22.102_Vnimani pomijivosti.html'
mv 'Samyutta Nikaya/Voditko (1).html' 'Samyutta Nikaya/SN22.99_Voditko (1).html'
mv 'Samyutta Nikaya/Voditko (2).html' 'Samyutta Nikaya/SN22.100_Voditko (2).html'
mv 'Samyutta Nikaya/Vstup do proudu.html' 'Samyutta Nikaya/SN24.1_Vstup do proudu.html'
mv 'Samyutta Nikaya/Yamaka.html' 'Samyutta Nikaya/SN22.85_Yamaka.html'
mv 'Samyutta Nikaya/Mys¦îlenky.html' 'Samyutta Nikaya/SN56.7_Mys¦îlenky.html'
mv 'Samyutta Nikaya/Neklid skrze ulpivani.html' 'Samyutta Nikaya/SN22.7_Neklid skrze ulpivani.html'
mv 'Samyutta Nikaya/Nemocen.html' 'Samyutta Nikaya/SN55.54_Nemocen.html'
mv 'Samyutta Nikaya/Nepravidelne poradi.html' 'Samyutta Nikaya/SN48.40_Nepravidelne poradi.html'
mv 'Samyutta Nikaya/O samote.html' 'Samyutta Nikaya/SN36.11_O samote.html'
mv 'Samyutta Nikaya/Ocean.html' 'Samyutta Nikaya/SN35.228_Ocean.html'
mv 'Samyutta Nikaya/Parileyya.html' 'Samyutta Nikaya/SN22.81_Parileyya.html'
mv 'Samyutta Nikaya/Podobenstvi o zelve.html' 'Samyutta Nikaya/SN35.240_Podobenstvi o zelve.html'
mv 'Samyutta Nikaya/Prodlevani (1).html' 'Samyutta Nikaya/SN45.11_Prodlevani (1).html'
mv 'Samyutta Nikaya/Prodlevani (2).html' 'Samyutta Nikaya/SN45.12_Prodlevani (2).html'
mv 'Samyutta Nikaya/Propast.html' 'Samyutta Nikaya/SN36.4_Propast.html'
mv 'Samyutta Nikaya/Pr¦îed ti¦üm nez¦î.html' 'Samyutta Nikaya/SN51.11_Pr¦îed ti¦üm nez¦î.html'
mv 'Samyutta Nikaya/Rozmy¦üs¦îleni¦ü.html' 'Samyutta Nikaya/SN56.8_Rozmy¦üs¦îleni¦ü.html'
mv 'Samyutta Nikaya/Sakkanamaka.html' 'Samyutta Nikaya/SN10.2_Sakkanamaka.html'
mv 'Samyutta Nikaya/Sbe¦îrac¦î almuz¦îen.html' 'Samyutta Nikaya/SN22.80_Sbe¦îrac¦î almuz¦îen.html'
mv 'Samyutta Nikaya/Seminka.html' 'Samyutta Nikaya/SN22.54_Seminka.html'
mv 'Samyutta Nikaya/Strom Kimsuka.html' 'Samyutta Nikaya/SN35.245_Strom Kimsuka.html'
mv 'Samyutta Nikaya/Svazek jecmene.html' 'Samyutta Nikaya/SN35.248_Svazek jecmene.html'
mv 'Samyutta Nikaya/Te¦îlo.html' 'Samyutta Nikaya/SN46.2_Te¦îlo.html'
mv 'Samyutta Nikaya/Timbaruka.html' 'Samyutta Nikaya/SN12.18_Timbaruka.html'
mv 'Samyutta Nikaya/Upasena.html' 'Samyutta Nikaya/SN35.69_Upasena.html'
mv 'Samyutta Nikaya/Uplnkova noc.html' 'Samyutta Nikaya/SN22.82_Uplnkova noc.html'
mv 'Samyutta Nikaya/Ve Versich.html' 'Samyutta Nikaya/SN14.16_Ve Versich.html'
mv 'Samyutta Nikaya/Vy¦üchodni¦ü vra¦ütnice.html' 'Samyutta Nikaya/SN48.44_Vy¦üchodni¦ü vra¦ütnice.html'
mv 'Samyutta Nikaya/Vznik.html' 'Samyutta Nikaya/SN47.42_Vznik.html'
mv 'Samyutta Nikaya/Z bli¦üzke¦üho br¦îehu.html' 'Samyutta Nikaya/SN51.1_Z bli¦üzke¦üho br¦îehu.html'
mv 'Samyutta Nikaya/Zlodej pachu.html' 'Samyutta Nikaya/SN9.14_Zlodej pachu.html'
