#!/bin/bash
. ~/.bashrc

function bp() 
{ 
v	sed -e 's/.*percentage[^0-9]*\([0-9]*\).*/\1/'
}

function battery-wait()
{
        p=80
        [ -n "$1" ] && p="$1"

	x=$(termux-battery-status)
	[ -z "$quiet" ] && echo $x >&2

	echo $x | grep -i discharging && termux-wake-lock && wl=y

        while sleep 60; do
		x=$(termux-battery-status)
		[ -z "$quiet" ] && echo $x >&2
		bp=$(echo $x | sed -e 's/.*percentage[^0-9]*\([0-9]*\).*/\1/')

                if [ "${bp}" -ge "$p" ]; then
                        termux-notification -c "battery > $p"
                        termux-tts-speak 'battery charged'
                        break
                fi
        done
        [ "$wl" = y ] && termux-wake-unlock
}

battery-wait "$@"
read
