#!/bin/bash
. ~/.bashrc

function bp() { termux-battery-status |grep percentage|sed -e 's/[^0-9]*\([0-9]*\).*/\1/';}; export  -f bp;

function battery-wait()
{
        p=80
        [ -n "$1" ] && p="$1"

	termux-battery-status | grep -vi discharging && wl=y

        [ "$wl" = y ] && termux-wake-lock
        while sleep 60; do
                if [ "$(bp)" -ge "$p" ]; then
                        termux-notification -c "battery > $p"
                        termux-tts-speak 'battery charged'
                        break
                fi
        done
        [ "$wl" = y ] && termux-wake-unlock
}

battery-wait "$@"

