#!/bin/bash
. ~/.bashrc

function get_val() 
{ 
	sed -e "s/.*${1}[^0-9]*\([0-9]*\).*/\1/"
}

function battery-wait()
{
        p=80
	mt=40
        [ -n "$1" ] && p="$1"

	x=$(termux-battery-status)
	[ -z "$quiet" ] && echo $x >&2

	echo $x | grep -i discharging && termux-wake-lock && wl=y

        while sleep 60; do
		x=$(termux-battery-status)
		[ -z "$quiet" ] && echo $x >&2
		bp=$(echo $x | get_val percentage)
		t=$(echo $x | get_val temperature)

                if [ "${bp}" -ge "$p" ]; then
                        termux-notification -c "battery > $p"
                        termux-tts-speak "battery charged to $bp"
                        break
                fi

 	        if [ "${t}" -ge "$mt" ]; then
                        termux-tts-speak "temp over $t"
                fi
        done
        [ "$wl" = y ] && termux-wake-unlock
}

battery-wait "$@"
read
