mv 'Anguttara Nikaya/(Po)ka¦üra¦üni¦ü.html' 'Anguttara Nikaya/AN5.167_(Po)ka¦üra¦üni¦ü.html'
mv 'Anguttara Nikaya/Araka.html' 'Anguttara Nikaya/AN7.74_Araka.html'
mv 'Anguttara Nikaya/A¦ünanda.html' 'Anguttara Nikaya/AN9.37_A¦ünanda.html'
mv 'Anguttara Nikaya/Ba¦üzlivost.html' 'Anguttara Nikaya/AN5.158_Ba¦üzlivost.html'
mv 'Anguttara Nikaya/Bojovni¦ük.html' 'Anguttara Nikaya/AN4.181_Bojovni¦ük.html'
mv 'Anguttara Nikaya/Bytosti.html' 'Anguttara Nikaya/AN9.24_Bytosti.html'
mv 'Anguttara Nikaya/Brahmanske pravdy.html' 'Anguttara Nikaya/AN4.185_Brahmanske pravdy.html'
mv 'Anguttara Nikaya/Brahma¦üni.html' 'Anguttara Nikaya/AN9.38_Brahma¦üni.html'
mv 'Anguttara Nikaya/Byt sdruzovan.html' 'Anguttara Nikaya/AN3.26_Byt sdruzovan.html'
mv 'Anguttara Nikaya/Byti (Zivot).html' 'Anguttara Nikaya/AN3.76_Byti (Zivot).html'
mv 'Anguttara Nikaya/Chteni a usilovani.html' 'Anguttara Nikaya/AN3.77_Chteni a usilovani.html'
mv 'Anguttara Nikaya/C¦îiny.html' 'Anguttara Nikaya/AN4.115_C¦îiny.html'
mv 'Anguttara Nikaya/Diamant.html' 'Anguttara Nikaya/AN3.25_Diamant.html'
mv 'Anguttara Nikaya/Dluh.html' 'Anguttara Nikaya/AN6.45_Dluh.html'
mv 'Anguttara Nikaya/Hluboko potopeny.html' 'Anguttara Nikaya/AN4.86_Hluboko potopeny.html'
mv 'Anguttara Nikaya/Hmota:Tvar.html' 'Anguttara Nikaya/AN4.65_Hmota:Tvar.html'
mv 'Anguttara Nikaya/Hne¦îv.html' 'Anguttara Nikaya/AN4.43_Hne¦îv.html'
mv 'Anguttara Nikaya/Jeden Narus¦îuje.html' 'Anguttara Nikaya/AN5.142_Jeden Narus¦îuje.html'
mv 'Anguttara Nikaya/Kalakarama sutta.html' 'Anguttara Nikaya/AN4.24_Kalakarama sutta.html'
mv 'Anguttara Nikaya/Kamenny¦ü pili¦ür¦î.html' 'Anguttara Nikaya/AN9.26_Kamenny¦ü pili¦ür¦î.html'
mv 'Anguttara Nikaya/Kladeni¦ü ota¦üzek.html' 'Anguttara Nikaya/AN5.165_Kladeni¦ü ota¦üzek.html'
mv 'Anguttara Nikaya/Koka¦älika.html' 'Anguttara Nikaya/AN10.89_Koka¦älika.html'
mv 'Anguttara Nikaya/Kotthita.html' 'Anguttara Nikaya/AN9.13_Kotthita.html'
mv 'Anguttara Nikaya/Kra¦üva.html' 'Anguttara Nikaya/AN9.35_Kra¦üva.html'
mv 'Anguttara Nikaya/Laska a Nenavist.html' 'Anguttara Nikaya/AN4.200_Laska a Nenavist.html'
mv 'Anguttara Nikaya/Lev.html' 'Anguttara Nikaya/AN4.33_Lev.html'
mv 'Anguttara Nikaya/Mallika.html' 'Anguttara Nikaya/AN4.197_Mallika.html'
mv 'Anguttara Nikaya/Manz¦îelky.html' 'Anguttara Nikaya/AN7.63_Manz¦îelky.html'
mv 'Anguttara Nikaya/Migasala.html' 'Anguttara Nikaya/AN6.44_Migasala.html'
mv 'Anguttara Nikaya/Mniska.html' 'Anguttara Nikaya/AN4.159_Mniska.html'
mv 'Anguttara Nikaya/Naga.html' 'Anguttara Nikaya/AN6.43_Naga.html'
mv 'Anguttara Nikaya/Nandamata.html' 'Anguttara Nikaya/AN7.53_Nandamata.html'
mv 'Anguttara Nikaya/Nazirani.html' 'Anguttara Nikaya/AN4.89_Nazirani.html'
mv 'Anguttara Nikaya/Nebezpeci.html' 'Anguttara Nikaya/AN3.62_Nebezpeci.html'
mv 'Anguttara Nikaya/Odloucen.html' 'Anguttara Nikaya/AN4.38_Odloucen.html'
mv 'Anguttara Nikaya/Odstrane¦îni¦ü rozhor¦îc¦îeni¦ü.html' 'Anguttara Nikaya/AN5.162_Odstrane¦îni¦ü rozhor¦îc¦îeni¦ü.html'
mv 'Anguttara Nikaya/Okovy.html' 'Anguttara Nikaya/AN4.88_Okovy.html'
mv 'Anguttara Nikaya/Ota¦üzky.html' 'Anguttara Nikaya/AN4.42_Ota¦üzky.html'
mv 'Anguttara Nikaya/Pacetana.html' 'Anguttara Nikaya/AN3.15_Pacetana.html'
mv 'Anguttara Nikaya/Podmi¦ünky sve¦îta (1).html' 'Anguttara Nikaya/AN8.5_Podmi¦ünky sve¦îta (1).html'
mv 'Anguttara Nikaya/Podmi¦ünky sve¦îta (2).html' 'Anguttara Nikaya/AN8.6_Podmi¦ünky sve¦îta (2).html'
mv 'Anguttara Nikaya/Potaliya.html' 'Anguttara Nikaya/AN4.100_Potaliya.html'
mv 'Anguttara Nikaya/Poleno z pohr¦îebni¦ü hranice.html' 'Anguttara Nikaya/AN4.95_Poleno z pohr¦îebni¦ü hranice.html'
mv 'Anguttara Nikaya/Poutavy¦ü (1).html' 'Anguttara Nikaya/AN8.17_Poutavy¦ü (1).html'
mv 'Anguttara Nikaya/Pronikavy.html' 'Anguttara Nikaya/AN6.63_Pronikavy.html'
mv 'Anguttara Nikaya/R¦îec¦î jako hnu¦Őj (lejno).html' 'Anguttara Nikaya/AN3.28_R¦îec¦î jako hnu¦Őj (lejno).html'
mv 'Anguttara Nikaya/Sexualni styk.html' 'Anguttara Nikaya/AN7.50_Sexualni styk.html'
mv 'Anguttara Nikaya/Situace.html' 'Anguttara Nikaya/AN5.48_Situace.html'
mv 'Anguttara Nikaya/Syn.html' 'Anguttara Nikaya/AN4.87_Syn.html'
mv 'Anguttara Nikaya/Uvedomeni smrti.html' 'Anguttara Nikaya/AN6.19_Uvedomeni smrti.html'
mv 'Anguttara Nikaya/Vnimani.html' 'Anguttara Nikaya/AN7.49_Vnimani.html'
mv 'Anguttara Nikaya/Zakor¦îene¦îny.html' 'Anguttara Nikaya/AN8.83_Zakor¦îene¦îny.html'
mv 'Anguttara Nikaya/Zmije.html' 'Anguttara Nikaya/AN4.110_Zmije.html'
mv 'Anguttara Nikaya/Poutavy¦ü (2).html' 'Anguttara Nikaya/AN8.18_Poutavy¦ü (2).html'
mv 'Anguttara Nikaya/Sama¦ädhi.html' 'Anguttara Nikaya/AN4.41_Sama¦ädhi.html'
mv 'Anguttara Nikaya/Sariputta.html' 'Anguttara Nikaya/AN3.33_Sariputta.html'
mv 'Anguttara Nikaya/Sve¦ît.html' 'Anguttara Nikaya/AN4.23_Sve¦ît.html'
mv 'Anguttara Nikaya/S¦îpatne¦î adresovana¦ü r¦îec¦î.html' 'Anguttara Nikaya/AN5.157_S¦îpatne¦î adresovana¦ü r¦îec¦î.html'
mv 'Anguttara Nikaya/Te¦ümata.html' 'Anguttara Nikaya/AN5.57_Te¦ümata.html'
mv 'Anguttara Nikaya/Uda¦äyi¦ä.html' 'Anguttara Nikaya/AN5.159_Uda¦äyi¦ä.html'
mv 'Anguttara Nikaya/Usta¦üni¦ü.html' 'Anguttara Nikaya/AN5.166_Usta¦üni¦ü.html'
mv 'Anguttara Nikaya/V jake¦ümkoli mi¦üste¦î.html' 'Anguttara Nikaya/AN5.134_V jake¦ümkoli mi¦üste¦î.html'
mv 'Anguttara Nikaya/Vappa.html' 'Anguttara Nikaya/AN4.195_Vappa.html'
mv 'Anguttara Nikaya/Ve Str¦îedu.html' 'Anguttara Nikaya/AN6.61_Ve Str¦îedu.html'
mv 'Anguttara Nikaya/Vr¦îed.html' 'Anguttara Nikaya/AN9.15_Vr¦îed.html'
mv 'Anguttara Nikaya/Zhnusenost.html' 'Anguttara Nikaya/AN3.27_Zhnusenost.html'
mv 'Anguttara Nikaya/Zlost (1 & 2).html' 'Anguttara Nikaya/AN9.29_Zlost (1 & 2).html'
