mv './Anguttara Nikaya/AN7.74_Araka.html' './Anguttara Nikaya/AN7.74_Araka.html'
mv './Anguttara Nikaya/AN9.37_A¦ünanda.html' './Anguttara Nikaya/AN9.37_Ánanda.html'
mv './Anguttara Nikaya/AN4.181_Bojovni¦ük.html' './Anguttara Nikaya/AN4.181_Bojovník.html'
mv './Anguttara Nikaya/AN9.24_Bytosti.html' './Anguttara Nikaya/AN9.24_Bytosti.html'
mv './Anguttara Nikaya/AN9.38_Brahma¦üni.html' './Anguttara Nikaya/AN9.38_Brahmáni.html'
mv './Anguttara Nikaya/AN3.26_Byt sdruzovan.html' './Anguttara Nikaya/AN3.26_Byt sdruzovan.html'
mv './Anguttara Nikaya/AN3.76_Byti (Zivot).html' './Anguttara Nikaya/AN3.76_Byti (Zivot).html'
mv './Anguttara Nikaya/AN3.77_Chteni a usilovani.html' './Anguttara Nikaya/AN3.77_Chteni a usilovani.html'
mv './Anguttara Nikaya/AN4.115_C¦îiny.html' './Anguttara Nikaya/AN4.115_Činy.html'
mv './Anguttara Nikaya/AN3.25_Diamant.html' './Anguttara Nikaya/AN3.25_Diamant.html'
mv './Anguttara Nikaya/AN6.45_Dluh.html' './Anguttara Nikaya/AN6.45_Dluh.html'
mv './Anguttara Nikaya/AN4.65_Hmota:Tvar.html' './Anguttara Nikaya/AN4.65_Hmota:Tvar.html'
mv './Anguttara Nikaya/AN4.43_Hne¦îv.html' './Anguttara Nikaya/AN4.43_Hněv.html'
mv './Anguttara Nikaya/AN4.24_Kalakarama sutta.html' './Anguttara Nikaya/AN4.24_Kalakarama sutta.html'
mv './Anguttara Nikaya/AN9.26_Kamenny¦ü pili¦ür¦î.html' './Anguttara Nikaya/AN9.26_Kamenný pilíř.html'
mv './Anguttara Nikaya/AN10.89_Koka¦älika.html' './Anguttara Nikaya/AN10.89_Kokālika.html'
mv './Anguttara Nikaya/AN9.13_Kotthita.html' './Anguttara Nikaya/AN9.13_Kotthita.html'
mv './Anguttara Nikaya/AN9.35_Kra¦üva.html' './Anguttara Nikaya/AN9.35_Kráva.html'
mv './Anguttara Nikaya/AN4.200_Laska a Nenavist.html' './Anguttara Nikaya/AN4.200_Laska a Nenavist.html'
mv './Anguttara Nikaya/AN4.33_Lev.html' './Anguttara Nikaya/AN4.33_Lev.html'
mv './Anguttara Nikaya/AN4.197_Mallika.html' './Anguttara Nikaya/AN4.197_Mallika.html'
mv './Anguttara Nikaya/AN6.44_Migasala.html' './Anguttara Nikaya/AN6.44_Migasala.html'
mv './Anguttara Nikaya/AN4.159_Mniska.html' './Anguttara Nikaya/AN4.159_Mniska.html'
mv './Anguttara Nikaya/AN6.43_Naga.html' './Anguttara Nikaya/AN6.43_Naga.html'
mv './Anguttara Nikaya/AN7.53_Nandamata.html' './Anguttara Nikaya/AN7.53_Nandamata.html'
mv './Anguttara Nikaya/AN3.62_Nebezpeci.html' './Anguttara Nikaya/AN3.62_Nebezpeci.html'
mv './Anguttara Nikaya/AN4.38_Odloucen.html' './Anguttara Nikaya/AN4.38_Odloucen.html'
mv './Anguttara Nikaya/AN4.88_Okovy.html' './Anguttara Nikaya/AN4.88_Okovy.html'
mv './Anguttara Nikaya/AN4.42_Ota¦üzky.html' './Anguttara Nikaya/AN4.42_Otázky.html'
mv './Anguttara Nikaya/AN3.15_Pacetana.html' './Anguttara Nikaya/AN3.15_Pacetana.html'
mv './Anguttara Nikaya/AN8.5_Podmi¦ünky sve¦îta (1).html' './Anguttara Nikaya/AN8.5_Podmínky světa (1).html'
mv './Anguttara Nikaya/AN4.100_Potaliya.html' './Anguttara Nikaya/AN4.100_Potaliya.html'
mv './Anguttara Nikaya/AN4.95_Poleno z pohr¦îebni¦ü hranice.html' './Anguttara Nikaya/AN4.95_Poleno z pohřební hranice.html'
mv './Anguttara Nikaya/AN8.17_Poutavy¦ü (1).html' './Anguttara Nikaya/AN8.17_Poutavý (1).html'
mv './Anguttara Nikaya/AN6.63_Pronikavy.html' './Anguttara Nikaya/AN6.63_Pronikavy.html'
mv './Anguttara Nikaya/AN7.50_Sexualni styk.html' './Anguttara Nikaya/AN7.50_Sexualni styk.html'
mv './Anguttara Nikaya/AN5.48_Situace.html' './Anguttara Nikaya/AN5.48_Situace.html'
mv './Anguttara Nikaya/AN4.87_Syn.html' './Anguttara Nikaya/AN4.87_Syn.html'
mv './Anguttara Nikaya/AN6.19_Uvedomeni smrti.html' './Anguttara Nikaya/AN6.19_Uvedomeni smrti.html'
mv './Anguttara Nikaya/AN7.49_Vnimani.html' './Anguttara Nikaya/AN7.49_Vnimani.html'
mv './Anguttara Nikaya/AN8.83_Zakor¦îene¦îny.html' './Anguttara Nikaya/AN8.83_Zakořeněny.html'
mv './Anguttara Nikaya/AN4.110_Zmije.html' './Anguttara Nikaya/AN4.110_Zmije.html'
mv './Anguttara Nikaya/AN8.18_Poutavy¦ü (2).html' './Anguttara Nikaya/AN8.18_Poutavý (2).html'
mv './Anguttara Nikaya/AN4.41_Sama¦ädhi.html' './Anguttara Nikaya/AN4.41_Samādhi.html'
mv './Anguttara Nikaya/AN4.23_Sve¦ît.html' './Anguttara Nikaya/AN4.23_Svět.html'
mv './Anguttara Nikaya/AN5.57_Te¦ümata.html' './Anguttara Nikaya/AN5.57_Témata.html'
mv './Anguttara Nikaya/AN5.159_Uda¦äyi¦ä.html' './Anguttara Nikaya/AN5.159_Udāyī.html'
mv './Anguttara Nikaya/AN5.166_Usta¦üni¦ü.html' './Anguttara Nikaya/AN5.166_Ustání.html'
mv './Anguttara Nikaya/AN5.134_V jake¦ümkoli mi¦üste¦î.html' './Anguttara Nikaya/AN5.134_V jakémkoli místě.html'
mv './Anguttara Nikaya/AN4.195_Vappa.html' './Anguttara Nikaya/AN4.195_Vappa.html'
mv './Anguttara Nikaya/AN6.61_Ve Str¦îedu.html' './Anguttara Nikaya/AN6.61_Ve Středu.html'
mv './Anguttara Nikaya/AN9.15_Vr¦îed.html' './Anguttara Nikaya/AN9.15_Vřed.html'
mv './Anguttara Nikaya/AN9.30_Zlost (2).html' './Anguttara Nikaya/AN9.30_Zlost (2).html'
mv './Anguttara Nikaya/AN5.167_(Po)ka¦üra¦üni¦ü.html' './Anguttara Nikaya/AN5.167_(Po)kárání.html'
mv './Anguttara Nikaya/AN5.158_Ba¦üzlivost.html' './Anguttara Nikaya/AN5.158_Bázlivost.html'
mv './Anguttara Nikaya/AN4.185_Brahmanske pravdy.html' './Anguttara Nikaya/AN4.185_Brahmanske pravdy.html'
mv './Anguttara Nikaya/AN4.86_Hluboko potopeny.html' './Anguttara Nikaya/AN4.86_Hluboko potopeny.html'
mv './Anguttara Nikaya/AN5.142_Jeden Narus¦îuje.html' './Anguttara Nikaya/AN5.142_Jeden Narušuje.html'
mv './Anguttara Nikaya/AN5.165_Kladeni¦ü ota¦üzek.html' './Anguttara Nikaya/AN5.165_Kladení otázek.html'
mv './Anguttara Nikaya/AN7.63_Manz¦îelky.html' './Anguttara Nikaya/AN7.63_Manželky.html'
mv './Anguttara Nikaya/AN4.89_Nazirani.html' './Anguttara Nikaya/AN4.89_Nazirani.html'
mv './Anguttara Nikaya/AN5.162_Odstrane¦îni¦ü rozhor¦îc¦îeni¦ü.html' './Anguttara Nikaya/AN5.162_Odstranění rozhořčení.html'
mv './Anguttara Nikaya/AN8.6_Podmi¦ünky sve¦îta (2).html' './Anguttara Nikaya/AN8.6_Podmínky světa (2).html'
mv './Anguttara Nikaya/AN3.28_R¦îec¦î jako hnu¦Őj (lejno).html' './Anguttara Nikaya/AN3.28_Řeč jako hnůj (lejno).html'
mv './Anguttara Nikaya/AN3.33_Sariputta.html' './Anguttara Nikaya/AN3.33_Sariputta.html'
mv './Anguttara Nikaya/AN5.157_S¦îpatne¦î adresovana¦ü r¦îec¦î.html' './Anguttara Nikaya/AN5.157_Špatně adresovaná řeč.html'
mv './Anguttara Nikaya/AN3.27_Zhnusenost.html' './Anguttara Nikaya/AN3.27_Zhnusenost.html'
mv './Anguttara Nikaya/AN9.29_Zlost (1).html' './Anguttara Nikaya/AN9.29_Zlost (1).html'
mv './Digha Nikaya/DN17_Kralovo zreknuti se.html' './Digha Nikaya/DN17_Kralovo zreknuti se.html'
mv './Digha Nikaya/DN11.85_Opora:zakladna.html' './Digha Nikaya/DN11.85_Opora:zakladna.html'
mv './Digha Nikaya/DN23_Pa¦äya¦äsi sutta.html' './Digha Nikaya/DN23_Pāyāsi sutta.html'
mv './Digha Nikaya/DN9_Stavy ve¦îdomi¦ü.html' './Digha Nikaya/DN9_Stavy vědomí.html'
mv './Digha Nikaya/DN25_Velky Lvi Rev k Udumbarikanum.html' './Digha Nikaya/DN25_Velky Lvi Rev k Udumbarikanum.html'
mv './Digha Nikaya/DN3_Zahanbena¦ü py¦ücha.html' './Digha Nikaya/DN3_Zahanbená pýcha.html'
mv './Digha Nikaya/DN27_Znalost Pocatku.html' './Digha Nikaya/DN27_Znalost Pocatku.html'
mv './Digha Nikaya/DN13_Cesta k Brahmovi (Bohu).html' './Digha Nikaya/DN13_Cesta k Brahmovi (Bohu).html'
mv './Digha Nikaya/DN26_Lvi rev k roztoceni kola.html' './Digha Nikaya/DN26_Lvi rev k roztoceni kola.html'
mv './Majjhima Nikaya/MN97_Dhananjani.html' './Majjhima Nikaya/MN97_Dhananjani.html'
mv './Majjhima Nikaya/MN140_Expozice Elementu:Prvku.html' './Majjhima Nikaya/MN140_Expozice Elementu:Prvku.html'
mv './Majjhima Nikaya/MN107_Ganaka Moggalla¦änovi.html' './Majjhima Nikaya/MN107_Ganaka Moggallānovi.html'
mv './Majjhima Nikaya/MN81_Hrnc¦îi¦ür¦î Ghatikara.html' './Majjhima Nikaya/MN81_Hrnčíř Ghatikara.html'
mv './Majjhima Nikaya/MN131_Jedna skvela noc.html' './Majjhima Nikaya/MN131_Jedna skvela noc.html'
mv './Majjhima Nikaya/MN74_K Dighanakhovi.html' './Majjhima Nikaya/MN74_K Dighanakhovi.html'
mv './Majjhima Nikaya/MN147_Kratsi sdeleni Rahulovi.html' './Majjhima Nikaya/MN147_Kratsi sdeleni Rahulovi.html'
mv './Majjhima Nikaya/MN135_Krats¦îi¦ü rozprava o kona¦üni¦ü.html' './Majjhima Nikaya/MN135_Kratší rozprava o konání.html'
mv './Majjhima Nikaya/MN75_Magandiya.html' './Majjhima Nikaya/MN75_Magandiya.html'
mv './Majjhima Nikaya/MN146_Nandakovo sdeleni.html' './Majjhima Nikaya/MN146_Nandakovo sdeleni.html'
mv './Majjhima Nikaya/MN86_O Angulimalovi.html' './Majjhima Nikaya/MN86_O Angulimalovi.html'
mv './Majjhima Nikaya/MN151_Oc¦îis¦ît¦îova¦üni¦ü almuz¦îni¦üho ji¦üdla.html' './Majjhima Nikaya/MN151_Očišťování almužního jídla.html'
mv './Majjhima Nikaya/MN66_Podobenstvi¦ü o kr¦îepelce.html' './Majjhima Nikaya/MN66_Podobenství o křepelce.html'
mv './Majjhima Nikaya/MN138_Rozbor uryvku recitace.html' './Majjhima Nikaya/MN138_Rozbor uryvku recitace.html'
mv './Majjhima Nikaya/MN143_Sdeleni Anathapindikovi.html' './Majjhima Nikaya/MN143_Sdeleni Anathapindikovi.html'
mv './Majjhima Nikaya/MN144_Sdeleni Channovi.html' './Majjhima Nikaya/MN144_Sdeleni Channovi.html'
mv './Majjhima Nikaya/MN148_S¦îest sad po s¦îesti.html' './Majjhima Nikaya/MN148_Šest sad po šesti.html'
mv './Majjhima Nikaya/MN101_V Devadaze.html' './Majjhima Nikaya/MN101_V Devadaze.html'
mv './Majjhima Nikaya/MN140_Vyklad prvku (elementu).html' './Majjhima Nikaya/MN140_Vyklad prvku (elementu).html'
mv './Majjhima Nikaya/MN139_Vy¦üklad o Bez-rozporu.html' './Majjhima Nikaya/MN139_Výklad o Bez-rozporu.html'
mv './Majjhima Nikaya/MN87_Zrozeno z Milovanych.html' './Majjhima Nikaya/MN87_Zrozeno z Milovanych.html'
mv './Majjhima Nikaya/MN79_Culasakuludayi Sutta.html' './Majjhima Nikaya/MN79_Culasakuludayi Sutta.html'
mv './Majjhima Nikaya/MN145_Doporuc¦îeni¦ü Punnovi.html' './Majjhima Nikaya/MN145_Doporučení Punnovi.html'
mv './Majjhima Nikaya/MN121_Kratsi rozprava o prazdnote.html' './Majjhima Nikaya/MN121_Kratsi rozprava o prazdnote.html'
mv './Majjhima Nikaya/MN1_O kor¦îeni vs¦îech ve¦îci¦ü.html' './Majjhima Nikaya/MN1_O kořeni všech věcí.html'
mv './Majjhima Nikaya/MN98_Va¦äsettha Sutta.html' './Majjhima Nikaya/MN98_Vāsettha Sutta.html'
mv './Samyutta Nikaya/SN4.1_Asketicka¦ü praxe.html' './Samyutta Nikaya/SN4.1_Asketická praxe.html'
mv './Samyutta Nikaya/SN12.45_At -atika.html' './Samyutta Nikaya/SN12.45_At -atika.html'
mv './Samyutta Nikaya/SN22.38_A¦änanda.html' './Samyutta Nikaya/SN22.38_Ānanda.html'
mv './Samyutta Nikaya/SN51.15_Brahman Unnabha.html' './Samyutta Nikaya/SN51.15_Brahman Unnabha.html'
mv './Samyutta Nikaya/SN22.22_Br¦îemeno.html' './Samyutta Nikaya/SN22.22_Břemeno.html'
mv './Samyutta Nikaya/SN22.79_Byt pohlcen.html' './Samyutta Nikaya/SN22.79_Byt pohlcen.html'
mv './Samyutta Nikaya/SN22.44_Cesta.html' './Samyutta Nikaya/SN22.44_Cesta.html'
mv './Samyutta Nikaya/SN14.13_Cihlova Hala.html' './Samyutta Nikaya/SN14.13_Cihlova Hala.html'
mv './Samyutta Nikaya/SN7.1_Dhananjani.html' './Samyutta Nikaya/SN7.1_Dhananjani.html'
mv './Samyutta Nikaya/SN22.56_Faze agregatu ulpivani.html' './Samyutta Nikaya/SN22.56_Faze agregatu ulpivani.html'
mv './Samyutta Nikaya/SN56.30_Gavampati.html' './Samyutta Nikaya/SN56.30_Gavampati.html'
mv './Samyutta Nikaya/SN22.55_Genialni prohlaseni.html' './Samyutta Nikaya/SN22.55_Genialni prohlaseni.html'
mv './Samyutta Nikaya/SN10.1_Indaka.html' './Samyutta Nikaya/SN10.1_Indaka.html'
mv './Samyutta Nikaya/SN16.3_Jako mesic.html' './Samyutta Nikaya/SN16.3_Jako mesic.html'
mv './Samyutta Nikaya/SN38.1_Jambukhadaka.html' './Samyutta Nikaya/SN38.1_Jambukhadaka.html'
mv './Samyutta Nikaya/SN47.6_Jestrab.html' './Samyutta Nikaya/SN47.6_Jestrab.html'
mv './Samyutta Nikaya/SN12.46_Jisty Brahman.html' './Samyutta Nikaya/SN12.46_Jisty Brahman.html'
mv './Samyutta Nikaya/SN7.11_Kasi Bha¦äradva¦äja.html' './Samyutta Nikaya/SN7.11_Kasi Bhāradvāja.html'
mv './Samyutta Nikaya/SN22.89_Khemaka.html' './Samyutta Nikaya/SN22.89_Khemaka.html'
mv './Samyutta Nikaya/SN20.10_Koc¦îka.html' './Samyutta Nikaya/SN20.10_Kočka.html'
mv './Samyutta Nikaya/SN22.32_Krehky.html' './Samyutta Nikaya/SN22.32_Krehky.html'
mv './Samyutta Nikaya/SN22.95_Kus pe¦îny.html' './Samyutta Nikaya/SN22.95_Kus pěny.html'
mv './Samyutta Nikaya/SN35.95_Ma¦älunkyaputta.html' './Samyutta Nikaya/SN35.95_Mālunkyaputta.html'
mv './Samyutta Nikaya/SN47.20_Nejkrasnejsi divka v zemi.html' './Samyutta Nikaya/SN47.20_Nejkrasnejsi divka v zemi.html'
mv './Samyutta Nikaya/SN35.101_Neni vase.html' './Samyutta Nikaya/SN35.101_Neni vase.html'
mv './Samyutta Nikaya/SN36.12_Obloha.html' './Samyutta Nikaya/SN36.12_Obloha.html'
mv './Samyutta Nikaya/SN36.7_Osetrovna.html' './Samyutta Nikaya/SN36.7_Osetrovna.html'
mv './Samyutta Nikaya/SN35.241_Podobenstvi o velke klade.html' './Samyutta Nikaya/SN35.241_Podobenstvi o velke klade.html'
mv './Samyutta Nikaya/SN35.246_Prirovnani k loutne.html' './Samyutta Nikaya/SN35.246_Prirovnani k loutne.html'
mv './Samyutta Nikaya/SN14.7_Rozdilnost Vnimani.html' './Samyutta Nikaya/SN14.7_Rozdilnost Vnimani.html'
mv './Samyutta Nikaya/SN48.43_Sa¦äketa.html' './Samyutta Nikaya/SN48.43_Sāketa.html'
mv './Samyutta Nikaya/SN47.19_Sedaka.html' './Samyutta Nikaya/SN47.19_Sedaka.html'
mv './Samyutta Nikaya/SN22.57_Sedm pripadu.html' './Samyutta Nikaya/SN22.57_Sedm pripadu.html'
mv './Samyutta Nikaya/SN54.41_Spekulace o Svete.html' './Samyutta Nikaya/SN54.41_Spekulace o Svete.html'
mv './Samyutta Nikaya/SN7.2_S¦îpatne¦ü zacha¦üzeni¦ü.html' './Samyutta Nikaya/SN7.2_Špatné zacházení.html'
mv './Samyutta Nikaya/SN56.36_Tvorove¦ü.html' './Samyutta Nikaya/SN56.36_Tvorové.html'
mv './Samyutta Nikaya/SN22.87_Vakkali.html' './Samyutta Nikaya/SN22.87_Vakkali.html'
mv './Samyutta Nikaya/SN22.99_Voditko (1).html' './Samyutta Nikaya/SN22.99_Voditko (1).html'
mv './Samyutta Nikaya/SN22.100_Voditko (2).html' './Samyutta Nikaya/SN22.100_Voditko (2).html'
mv './Samyutta Nikaya/SN22.85_Yamaka.html' './Samyutta Nikaya/SN22.85_Yamaka.html'
mv './Samyutta Nikaya/SN56.7_Mys¦îlenky.html' './Samyutta Nikaya/SN56.7_Myšlenky.html'
mv './Samyutta Nikaya/SN22.7_Neklid skrze ulpivani.html' './Samyutta Nikaya/SN22.7_Neklid skrze ulpivani.html'
mv './Samyutta Nikaya/SN55.54_Nemocen.html' './Samyutta Nikaya/SN55.54_Nemocen.html'
mv './Samyutta Nikaya/SN36.11_O samote.html' './Samyutta Nikaya/SN36.11_O samote.html'
mv './Samyutta Nikaya/SN35.228_Ocean.html' './Samyutta Nikaya/SN35.228_Ocean.html'
mv './Samyutta Nikaya/SN22.81_Parileyya.html' './Samyutta Nikaya/SN22.81_Parileyya.html'
mv './Samyutta Nikaya/SN45.11_Prodlevani (1).html' './Samyutta Nikaya/SN45.11_Prodlevani (1).html'
mv './Samyutta Nikaya/SN45.12_Prodlevani (2).html' './Samyutta Nikaya/SN45.12_Prodlevani (2).html'
mv './Samyutta Nikaya/SN36.4_Propast.html' './Samyutta Nikaya/SN36.4_Propast.html'
mv './Samyutta Nikaya/SN56.8_Rozmy¦üs¦îleni¦ü.html' './Samyutta Nikaya/SN56.8_Rozmýšlení.html'
mv './Samyutta Nikaya/SN10.2_Sakkanamaka.html' './Samyutta Nikaya/SN10.2_Sakkanamaka.html'
mv './Samyutta Nikaya/SN22.80_Sbe¦îrac¦î almuz¦îen.html' './Samyutta Nikaya/SN22.80_Sběrač almužen.html'
mv './Samyutta Nikaya/SN22.54_Seminka.html' './Samyutta Nikaya/SN22.54_Seminka.html'
mv './Samyutta Nikaya/SN35.248_Svazek jecmene.html' './Samyutta Nikaya/SN35.248_Svazek jecmene.html'
mv './Samyutta Nikaya/SN46.2_Te¦îlo.html' './Samyutta Nikaya/SN46.2_Tělo.html'
mv './Samyutta Nikaya/SN12.18_Timbaruka.html' './Samyutta Nikaya/SN12.18_Timbaruka.html'
mv './Samyutta Nikaya/SN35.69_Upasena.html' './Samyutta Nikaya/SN35.69_Upasena.html'
mv './Samyutta Nikaya/SN14.16_Ve Versich.html' './Samyutta Nikaya/SN14.16_Ve Versich.html'
mv './Samyutta Nikaya/SN47.42_Vznik.html' './Samyutta Nikaya/SN47.42_Vznik.html'
mv './Samyutta Nikaya/SN51.1_Z bli¦üzke¦üho br¦îehu.html' './Samyutta Nikaya/SN51.1_Z blízkého břehu.html'
mv './Samyutta Nikaya/SN9.14_Zlodej pachu.html' './Samyutta Nikaya/SN9.14_Zlodej pachu.html'
mv './Samyutta Nikaya/SN22.76_Arrahanti.html' './Samyutta Nikaya/SN22.76_Arrahanti.html'
mv './Samyutta Nikaya/SN42.6_Asibandhakaputta.html' './Samyutta Nikaya/SN42.6_Asibandhakaputta.html'
mv './Samyutta Nikaya/SN3.22_Babic¦îka.html' './Samyutta Nikaya/SN3.22_Babička.html'
mv './Samyutta Nikaya/SN48.42_Brahman Unnabha (Indriyasamyutta).html' './Samyutta Nikaya/SN48.42_Brahman Unnabha (Indriyasamyutta).html'
mv './Samyutta Nikaya/SN35.116_Dojit na konec sveta 2.html' './Samyutta Nikaya/SN35.116_Dojit na konec sveta 2.html'
mv './Samyutta Nikaya/SN56.39_Hranic¦îni¦ü pili¦ür¦î.html' './Samyutta Nikaya/SN56.39_Hraniční pilíř.html'
mv './Samyutta Nikaya/SN4.2_Kra¦ülovsky¦ü slon.html' './Samyutta Nikaya/SN4.2_Královský slon.html'
mv './Samyutta Nikaya/SN41.4_Mahaku¦Őv za¦üzrak.html' './Samyutta Nikaya/SN41.4_Mahakův zázrak.html'
mv './Samyutta Nikaya/SN35.238_Podobenstvi o Zmijich.html' './Samyutta Nikaya/SN35.238_Podobenstvi o Zmijich.html'
mv './Samyutta Nikaya/SN22.43_Sa¦üm Sobe¦î Ostrovem.html' './Samyutta Nikaya/SN22.43_Sám Sobě Ostrovem.html'
mv './Samyutta Nikaya/SN56.35_Sto kopi¦ü.html' './Samyutta Nikaya/SN56.35_Sto kopí.html'
mv './Samyutta Nikaya/SN22.102_Vnimani pomijivosti.html' './Samyutta Nikaya/SN22.102_Vnimani pomijivosti.html'
mv './Samyutta Nikaya/SN24.1_Vstup do proudu.html' './Samyutta Nikaya/SN24.1_Vstup do proudu.html'
mv './Samyutta Nikaya/SN48.40_Nepravidelne poradi.html' './Samyutta Nikaya/SN48.40_Nepravidelne poradi.html'
mv './Samyutta Nikaya/SN35.240_Podobenstvi o zelve.html' './Samyutta Nikaya/SN35.240_Podobenstvi o zelve.html'
mv './Samyutta Nikaya/SN51.11_Pr¦îed ti¦üm nez¦î.html' './Samyutta Nikaya/SN51.11_Před tím než.html'
mv './Samyutta Nikaya/SN35.245_Strom Kimsuka.html' './Samyutta Nikaya/SN35.245_Strom Kimsuka.html'
mv './Samyutta Nikaya/SN22.82_Uplnkova noc.html' './Samyutta Nikaya/SN22.82_Uplnkova noc.html'
mv './Samyutta Nikaya/SN48.44_Vy¦üchodni¦ü vra¦ütnice.html' './Samyutta Nikaya/SN48.44_Východní vrátnice.html'
mv './Khuddaka Nikaya - Petavatthu/Pv1.12_Had.html' './Khuddaka Nikaya - Petavatthu/Pv1.12_Had.html'
mv './Khuddaka Nikaya - Petavatthu/Pv2.5_Mattakundali.html' './Khuddaka Nikaya - Petavatthu/Pv2.5_Mattakundali.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp1.8_Miluji¦üci¦ü Laskavost.html' './Khuddaka Nikaya - Suttanipāta/Snp1.8_Milující Laskavost.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp2.3_Mora¦ülni¦ü ostuda.html' './Khuddaka Nikaya - Suttanipāta/Snp2.3_Morální ostuda.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp2.3_Mrs¦îina.html' './Khuddaka Nikaya - Suttanipāta/Snp2.3_Mršina.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp1.7_Vyvrhel.html' './Khuddaka Nikaya - Suttanipāta/Snp1.7_Vyvrhel.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp1.5_Cunda.html' './Khuddaka Nikaya - Suttanipāta/Snp1.5_Cunda.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp1.4_Kasibha¦äradva¦äja.html' './Khuddaka Nikaya - Suttanipāta/Snp1.4_Kasibhāradvāja.html'
mv './Khuddaka Nikaya - Suttanipāta/Snp1.11_Vi¦üte¦îzstvi¦ü.html' './Khuddaka Nikaya - Suttanipāta/Snp1.11_Vítězství.html'
