mv 'Majjhima Nikaya/Culasakuludayi Sutta.html' 'Majjhima Nikaya/MN79_Culasakuludayi Sutta.html'
mv 'Majjhima Nikaya/Dhananjani.html' 'Majjhima Nikaya/MN97_Dhananjani.html'
mv 'Majjhima Nikaya/Doporuc¦îeni¦ü Punnovi.html' 'Majjhima Nikaya/MN145_Doporuc¦îeni¦ü Punnovi.html'
mv 'Majjhima Nikaya/Expozice Elementu:Prvku.html' 'Majjhima Nikaya/MN140_Expozice Elementu:Prvku.html'
mv 'Majjhima Nikaya/Ganaka Moggalla¦änovi.html' 'Majjhima Nikaya/MN107_Ganaka Moggalla¦änovi.html'
mv 'Majjhima Nikaya/Hrnc¦îi¦ür¦î Ghatikara.html' 'Majjhima Nikaya/MN81_Hrnc¦îi¦ür¦î Ghatikara.html'
mv 'Majjhima Nikaya/Jedna skvela noc.html' 'Majjhima Nikaya/MN131_Jedna skvela noc.html'
mv 'Majjhima Nikaya/K Dighanakhovi.html' 'Majjhima Nikaya/MN74_K Dighanakhovi.html'
mv 'Majjhima Nikaya/Kratsi rozprava o prazdnote.html' 'Majjhima Nikaya/MN121_Kratsi rozprava o prazdnote.html'
mv 'Majjhima Nikaya/Kratsi sdeleni Rahulovi.html' 'Majjhima Nikaya/MN147_Kratsi sdeleni Rahulovi.html'
mv 'Majjhima Nikaya/Krats¦îi¦ü rozprava o kona¦üni¦ü.html' 'Majjhima Nikaya/MN135_Krats¦îi¦ü rozprava o kona¦üni¦ü.html'
mv 'Majjhima Nikaya/Magandiya.html' 'Majjhima Nikaya/MN75_Magandiya.html'
mv 'Majjhima Nikaya/Nandakovo sdeleni.html' 'Majjhima Nikaya/MN146_Nandakovo sdeleni.html'
mv 'Majjhima Nikaya/O Angulimalovi.html' 'Majjhima Nikaya/MN86_O Angulimalovi.html'
mv 'Majjhima Nikaya/O kor¦îeni vs¦îech ve¦îci¦ü.html' 'Majjhima Nikaya/MN1_O kor¦îeni vs¦îech ve¦îci¦ü.html'
mv 'Majjhima Nikaya/Oc¦îis¦ît¦îova¦üni¦ü almuz¦îni¦üho ji¦üdla.html' 'Majjhima Nikaya/MN151_Oc¦îis¦ît¦îova¦üni¦ü almuz¦îni¦üho ji¦üdla.html'
mv 'Majjhima Nikaya/Podobenstvi¦ü o kr¦îepelce.html' 'Majjhima Nikaya/MN66_Podobenstvi¦ü o kr¦îepelce.html'
mv 'Majjhima Nikaya/Rozbor uryvku recitace.html' 'Majjhima Nikaya/MN138_Rozbor uryvku recitace.html'
mv 'Majjhima Nikaya/Sdeleni Anathapindikovi.html' 'Majjhima Nikaya/MN143_Sdeleni Anathapindikovi.html'
mv 'Majjhima Nikaya/Sdeleni Channovi.html' 'Majjhima Nikaya/MN144_Sdeleni Channovi.html'
mv 'Majjhima Nikaya/S¦îest sad po s¦îesti.html' 'Majjhima Nikaya/MN148_S¦îest sad po s¦îesti.html'
mv 'Majjhima Nikaya/V Devadaze.html' 'Majjhima Nikaya/MN101_V Devadaze.html'
mv 'Majjhima Nikaya/Va¦äsettha Sutta.html' 'Majjhima Nikaya/MN98_Va¦äsettha Sutta.html'
mv 'Majjhima Nikaya/Vyklad prvku (elementu).html' 'Majjhima Nikaya/MN140_Vyklad prvku (elementu).html'
mv 'Majjhima Nikaya/Vy¦üklad o Bez-rozporu.html' 'Majjhima Nikaya/MN139_Vy¦üklad o Bez-rozporu.html'
mv 'Majjhima Nikaya/Zrozeno z Milovanych.html' 'Majjhima Nikaya/MN87_Zrozeno z Milovanych.html'
